dist: xenial
os: linux
language: generic

env:
- HUGO_VERSION="0.55.6"

install:
  - wget -q -O hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb
  - sudo dpkg -i hugo.deb

script:
  - hugo version
  - hugo # This commands builds your website on travis
  - ls -l public

deploy:
  local_dir: public # Default static site output dir for Hugo
  provider: pages
  skip_cleanup: true
  github_token: $GH_REPO_TOKEN # Set in travis-ci settings
  on:
    branch: master

notifications:
  email:
    on_failure: always
